### ISSUE TITLE
Define Client Settings Grouping

### ISSUE THREAD

**Issue by ManuelRauber** [IdentityServer/Thinktecture.IdentityServer3.Admin.Client#4]
Please describe which settings should be grouped together for a tabbed interface of client settings.

**Comment by leastprivilege** [comment]
OK - since client settings are pretty complex - I imagine that UI to be "tabbed" - to group together things that belong together and to not overwhelm the user with all settings on a single screen

### Tab1: General

Enabled
ClientName
ClientId
ClientUri
LogoUri
ClientSecrets
Flow
RequireConsent
AllowRememberConsent

### Tab2: URIs and Restrictions

RedirectUris
PostLogoutRedirectUris
ScopeRestrictions
IdentityProviderRestrictions
CustomGrantTypeRestrictions
EnableLocalLogin

### Tab 3 - Tokens and Lifetimes

IdentityTokenLifetime
AccessTokenLifetime
AuthorizationCodeLifetime
AbsoluteRefreshTokenLifetime
SlidingRefreshTokenLifetime
RefreshTokenUsage
RefreshTokenExpiration
AccessTokenType
IncludeJwtId

(it would be nice if all lifetime had default values to choose from 1 hour, 1 day, 1 way, 1 month, 1 year)

### Tab 4 Client Claims

Claims
AlwaysSendClientClient
PrefixClientClaims


You could use the doc text for each setting as a "tool tip"

**Comment by ManuelRauber** [comment]
Grouping so far is done together with a select box for lifetimes.
